name: UnitTests
on:
  pull_request:
  push:

jobs:
  rpmlinter:
    runs-on: docker
    steps:
    - uses: actions/checkout@v4

    - name: rpmlinter
      run: |
        make spec
        docker run -v "$PWD"/python-boto.spec:/specs/python-boto.spec:z ubun/rpmlinter

  python_test:
    runs-on:
      group: centos7
      labels: centos7
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.6
        requirements:
          - requirements.txt

    steps:
    - uses: actions/checkout@v4

    - name: Install Python ${{ matrix.python-version }} dependencies
      run: |
        python${{ matrix.python-version }} -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        python -m pip install -r ${{ matrix.requirements }}

    - name: Run tests
      run: |
        source .venv/bin/activate
        python tests/test.py default
